import type { NextPage } from 'next';
import Head from 'next/head';
import teams from '../../data/teams.json';
import drivers from '../../data/drivers.json';
import { useState } from 'react';
import Image from 'next/image';
import Countdown from '../../components/Countdown';

const Race: NextPage = () => {
  const [team, setTeam] = useState('ferrari');

  return (
    <div className="text-center text-red-700">
      <Head>
        <title>Race | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex flex-col">
        <h1 className="text-white text-4xl font-semibold">Upcoming Race</h1>
        <div className="mx-auto h-0.5 w-80 bg-gradient-to-r from-redOne to-redTwo"></div>

        <div className="bg-gray my-4 mx-auto w-3/4 flex-1 rounded-xl flex">
          <div className="w-1/3 bg-gradient-to-b from-redOne to-redTwo rounded-lg flex flex-col items-start p-8">
            <h3 className="text-lg text-black font-semibold">Grand Prix</h3>
            <h4 className="text-lg text-white font-bold">Bahrain GP</h4>
            <h3 className="text-lg text-black font-semibold">Circuit</h3>
            <h4 className="text-lg text-white font-bold">
              Bahrain International Circuit
            </h4>
            <h3 className="text-lg text-black font-semibold">Date</h3>
            <h4 className="text-lg text-white font-bold">20th March 2022</h4>
            <h3 className="text-lg text-black font-semibold">Begins in</h3>
            <Countdown />
            <div className="flex items-center justify-center w-full">
              <Image
                src={require(`../../public/img/circuits/bahrain.png`)}
                width={251}
                height={180}
              />
            </div>
          </div>
          <div className="h-full p-8 flex-1">
            <div className="my-2">
              <h1 className="text-2xl text-white font-bold my-2 text-left">
                Teams
              </h1>
              <div className="flex w-full justify-between">
                {teams.map((team) => {
                  return (
                    <div
                      onClick={() => setTeam(team.key)}
                      className="cursor-pointer text-white"
                    >
                      <Image
                        src={require(`../../public/img/teams/${team.key}.png`)}
                        width={56}
                        height={56}
                      />
                    </div>
                  );
                })}
              </div>
            </div>
            <div className="my-2">
              <h1 className="text-2xl text-white font-bold my-2 text-left">
                Drivers
              </h1>
              <div className="flex">
                {/* @ts-ignore */}
                {drivers[`${team}`].map((driver) => {
                  return (
                    <div className="w-full">
                      <Image
                        src={require(`../../public/img/drivers/${driver.key}.png`)}
                        width={298}
                        height={249}
                      />
                      <h3 className="my-1 text-base font-semibold text-white">
                        {driver.name}
                      </h3>
                      <button className="my-1 bg-gradient-to-r from-redOne to-redTwo text-white font-semibold text-base py-2 px-10 rounded-xl">
                        Support
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Race;
