import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useMemo } from 'react';
import { useSelector } from 'react-redux';
import Navbar from '../../../components/Navbar';
import NFTCard from '../../../components/NFTCard';
import TEAMS from '../../../data/teams.json';
import withAuth from '../../../hoc/withAuth';
import useLeaderboard from '../../../hooks/useLeaderboard';
import useNFTMarket from '../../../hooks/useNFTMarket';
import { RootState } from '../../../store/rootReducer';

const MarketplaceNFT: NextPage = () => {
  const router = useRouter();
  const { nftId } = router.query;
  console.log(nftId);
  const { fetchLeaderboard } = useLeaderboard();

  const { address, token } = useSelector((state: RootState) => state.auth);

  const { marketItems } = useSelector((state: RootState) => state.marketplace);
  console.log(marketItems);

  const nft = useMemo(
    () => marketItems.find((item: any) => item.tokenId == nftId),
    [marketItems]
  );

  console.log(nft);

  const description = useMemo(
    () =>
      nft
        ? TEAMS.find((t) => t.livery === nft.image.split('/')[4])?.description
        : '',
    [nft]
  );

  const { buyItem } = useNFTMarket();

  return (
    <div className="text-center h-screen flex flex-col text-red-700">
      <Head>
        <title>NFT | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {nft && (
        <div className="flex-1 flex p-10">
          <div className="w-1/2 flex flex-col items-center">
            <NFTCard img={nft.image} />
          </div>
          <div className="w-1/2 text-left">
            <div>
              <h1 className="text-white text-4xl font-bold">{nft.name}</h1>
              <h3 className="text-white text-base my-3">
                Created by <span className="text-redOne">{nft.seller}</span>
              </h3>

              <p className="mt-5 text-white text-base">{description}</p>
            </div>
            <div className="flex w-3/5 justify-between">
              <div>
                <h3 className="text-gray-mute mt-8 text-xl font-semibold">
                  Price
                </h3>
                <div className="flex items-center mt-1">
                  <Image
                    src={require(`../../../public/img/matic.svg`)}
                    width={42}
                    height={21}
                  />
                  <span className="text-white text-2xl ml-2 font-bold">
                    {nft.price} MATIC
                  </span>
                </div>
              </div>
              <div>
                <h3 className="text-gray-mute mt-8 text-xl font-semibold">
                  Points
                </h3>
                <span className="text-white text-2xl mt-1 font-bold">
                  {nft.points}
                </span>
              </div>
            </div>
            {nft.seller !== address && (
              <button
                className="border-2 border-black mt-8 bg-gradient-to-r from-redOne to-redTwo rounded-lg w-64 py-2 text-white text-2xl font-bold"
                onClick={async () => {
                  await buyItem(nft, token);
                  await fetchLeaderboard();
                }}
              >
                Buy Now
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default withAuth(MarketplaceNFT);
