import Head from 'next/head';
import React from 'react';
import { useSelector } from 'react-redux';
import Navbar from '../components/Navbar';
import { RootState } from '../store/rootReducer';

const withAuth = (WrappedComponent: React.ComponentType) => {
  return (props: any) => {
    if (typeof window !== 'undefined') {
      const { authenticated } = useSelector((state: RootState) => state.auth);

      if (!authenticated) {
        return (
          <div className="h-screen flex flex-col text-center text-red-700">
            <Head>
              <title>Pit Stop</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="flex-1 flex items-center justify-center">
              <h1 className="text-2xl font-semibold text-white text-center">
                Sign in using MetaMask wallet to access this page.
              </h1>
            </div>
          </div>
        );
      }

      return <WrappedComponent {...props} />;
    }

    return null;
  };
};

export default withAuth;
