import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useMemo, useState } from 'react';
import Navbar from '../../components/Navbar';
import NFTCard from '../../components/NFTCard';
import TEAMS from '../../data/teams.json';
import useNFT from '../../hooks/useNFT';

const TEAMS1 = TEAMS.slice(0, 5);
const TEAMS2 = TEAMS.slice(5);

const Mint: NextPage = () => {
  const [teamKey, setTeamKey] = useState('mclaren');
  const livery = useMemo(
    () => TEAMS.find((t) => t.key === teamKey)?.name,
    [teamKey]
  );
  const description = useMemo(
    () => TEAMS.find((t) => t.key === teamKey)?.description,
    [teamKey]
  );

  const { mintNFT, fetchMintedNFTs } = useNFT();

  return (
    <div className="text-center h-screen flex flex-col text-red-700">
      <Head>
        <title>Mint | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex-1 flex p-10">
        <div className="w-1/2 flex flex-col items-center">
          <NFTCard team={teamKey} />
          <div className="flex mt-10">
            {TEAMS1.map((team) => {
              return (
                <div
                  onClick={() => setTeamKey(team.key)}
                  className="cursor-pointer text-white mx-1"
                >
                  <Image
                    src={require(`../../public/img/teams/${team.key}.png`)}
                    width={64}
                    height={64}
                  />
                </div>
              );
            })}
          </div>
          <div className="flex">
            {TEAMS2.map((team) => {
              return (
                <div
                  onClick={() => setTeamKey(team.key)}
                  className="cursor-pointer text-white mx-1"
                >
                  <Image
                    src={require(`../../public/img/teams/${team.key}.png`)}
                    width={64}
                    height={64}
                  />
                </div>
              );
            })}
          </div>
        </div>
        <div className="w-1/2 text-left">
          <div>
            <h3 className="text-gray-mute text-xl font-semibold">Livery</h3>
            <h1 className="text-white text-2xl font-bold">{livery}</h1>
            <p className="my-2 text-white text-base">{description}</p>
          </div>
          <button
            className="my-20 bg-gradient-to-r from-redTwo to-redTwo rounded-lg w-72 py-3 text-white text-2xl font-bold"
            onClick={async () => await mintNFT(teamKey)}
          >
            Mint
          </button>
        </div>
      </div>
    </div>
  );
};

export default Mint;
