import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useMemo, useState } from 'react';
import NFTCard from '../../components/NFTCard';
import teams from '../../data/teams.json';
const teams1 = teams.slice(0, 5);
const teams2 = teams.slice(5);

const Mint: NextPage = () => {
  const [team, setTeam] = useState('ferrari');
  const livery = useMemo(() => teams.find((t) => t.key === team)?.name, [team]);

  return (
    <div className="text-center text-red-700">
      <Head>
        <title>Mint | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex">
        <div className="w-1/2 p-10 flex flex-col items-center">
          <NFTCard team={team} />
          <div className="flex mt-10">
            {teams1.map((team) => {
              return (
                <div
                  onClick={() => setTeam(team.key)}
                  className="cursor-pointer text-white mx-1"
                >
                  <Image
                    src={require(`../../public/img/teams/${team.key}.png`)}
                    width={64}
                    height={64}
                  />
                </div>
              );
            })}
          </div>
          <div className="flex">
            {teams2.map((team) => {
              return (
                <div
                  onClick={() => setTeam(team.key)}
                  className="cursor-pointer text-white mx-1"
                >
                  <Image
                    src={require(`../../public/img/teams/${team.key}.png`)}
                    width={64}
                    height={64}
                  />
                </div>
              );
            })}
          </div>
        </div>
        <div className="w-1/2 p-10 text-left">
          <h3 className="text-gray-mute text-xl font-semibold">Livery</h3>
          <h1 className="text-white text-2xl font-bold">{livery}</h1>
        </div>
      </div>
    </div>
  );
};

export default Mint;
