import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../../components/Navbar';

const About: NextPage = () => {
  return (
    <div className="text-center text-red-700">
      <Head>
        <title>About | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>
  );
};

export default About;
