import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';
import useAuth from '../hooks/useAuth';
import { RootState } from '../store/rootReducer';

const Home: NextPage = () => {
  const { connect } = useAuth();
  const { address, authenticated } = useSelector(
    (state: RootState) => state.auth
  );

  useEffect(() => {
    connect();
  }, []);

  return (
    <div className="text-center text-red-700">
      <Head>
        <title>Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {authenticated && (
        <h1 className="text-xl font-semibold text-center text-white mx-auto">
          Welcome, {address}
        </h1>
      )}
    </div>
  );
};

export default Home;
