import type { NextPage } from 'next';
import Head from 'next/head';
import CompeteDashboard from '../../components/CompeteDashboard';
import Navbar from '../../components/Navbar';
import UpcomingRaceInfo from '../../components/UpcomingRaceInfo';
import withAuth from '../../hoc/withAuth';

const Race: NextPage = () => {
  return (
    <div className="h-screen text-center text-red-700">
      <Head>
        <title>Race | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          href="/favicon-16x16.png"
          sizes="16x16"
        />
      </Head>
      <Navbar />
      <div className="flex-1 flex flex-col min-h-full">
        <h1 className="text-white text-3xl font-semibold mt-4">
          Upcoming Race
        </h1>
        <div className="mx-auto h-0.5 w-80 bg-gradient-to-r from-redOne to-redTwo mt-1 mb-3"></div>

        <div
          className="bg-gray my-4 mx-auto w-3/4 flex-1 rounded-xl flex min-h-full"
          style={{ boxShadow: '0px -3px 86px 0px #00000080' }}
        >
          <UpcomingRaceInfo />
          <CompeteDashboard />
        </div>
      </div>
    </div>
  );
};

export default withAuth(Race);
