import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useSelector } from 'react-redux';
import GarageCard from '../../components/GarageCard';
import Navbar from '../../components/Navbar';
import { RootState } from '../../store/rootReducer';

const Garage: NextPage = () => {
  const { garage } = useSelector((state: RootState) => state.garage);

  return (
    <div className="h-screen text-center text-red-700">
      <Head>
        <title>Garage | Pit Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex-1 flex">
        <div className="w-1/2 p-10">
          <div className="bg-gray w-full h-full rounded-lg">
            <div className="flex">
              <Image
                src={require(`../../public/img/teams/ferrari.png`)}
                width={56}
                height={56}
              />
              <div className="flex flex-col">
                <h1 className="text-white text-base">Mizan Ali</h1>
                <h3 className="text-white text-base">@mizanxali</h3>
              </div>
              <Link href="/mint">
                <button className="border-2 border-black bg-gradient-to-r from-redOne to-redTwo rounded-lg px-10 py-2 font-semibold text-white text-xl">
                  Mint
                </button>
              </Link>
            </div>
          </div>
        </div>
        <div className="w-1/2 p-10">
          <div className="grid grid-cols-2 gap-10">
            {garage.map((garageItem: any) => (
              <GarageCard key={garageItem.itemId} NFT={garageItem} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Garage;
